name: game_note_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- LOCALIZAÇÃO ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2  # <--- ATUALIZADO AQUI (Era 0.19.0)
  # -------------------

  # --- FIREBASE ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  # ----------------

  # Outras dependências
  image_picker: ^1.1.2
  http: ^1.2.2
  path_provider: ^2.1.4
  path: ^1.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true